// Backend game constants — mirrors frontend constants/config.ts

module.exports = {
  MAX_HEARTS: 3,
  STREAK_TO_LEVEL_UP: 3,
  MIN_DIFFICULTY: 1,
  MAX_DIFFICULTY: 10,
  STARTING_DIFFICULTY: 1,

  EXP_PER_DIFFICULTY: 100,
  COMBO_BONUS_PER_STREAK: 50,
  MAX_COMBO_BONUS: 500,

  PASSIVE_EXP_INTERVAL: 30000,
  PASSIVE_EXP_AMOUNT: 5,

  INACTIVITY_TIMEOUT: 600000,
  QUESTIONS_PER_BATCH: 10,
};
